apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.TAIGA_HOSTNAME }}-tls
spec:
  secretName: {{ .Values.TAIGA_HOSTNAME }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: {{ .Values.TAIGA_HOSTNAME }}
  dnsNames:
  - {{ .Values.TAIGA_HOSTNAME }}
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - {{ .Values.TAIGA_HOSTNAME }}

