apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-events
  labels:
    app: {{ .Release.Name }}-events
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-events
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-events
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: events
          image: PUT YOUR REGISTRY HERE/k8s-taiga/taiga_events
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
          - name: TAIGA_RABBITMQ
            value: {{ .Release.Name }}-rabbitmq
          ports:
            - name: http
              containerPort: 8888
          imagePullSecrets:
            - name: gitlab-registry
