apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-temporary-redirect: "false"

  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
    - host:  {{ .Values.TAIGA_HOSTNAME }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-frontend
              servicePort: 8888
          - path: /api
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: 8000
          - path: /events
            backend:
              serviceName: {{ .Release.Name }}-events
              servicePort: 8888
  tls:
      - hosts:
          - {{ .Values.TAIGA_HOSTNAME }}
        secretName: {{ .Values.TAIGA_HOSTNAME }}-tls


